config/routes.rb
Capthur::Application.routes.draw do
  resources :capthurits

end

app/models/capthurit.rb
class Capthurit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/capthurits_controller.rb
require 'net/http'
require 'uri'

class CapthuritsController < ApplicationController
  before_action :set_capthurit, only: [:show, :edit, :update, :destroy]

  def follow
	x = 1
	url = URI.parse('http://bbcwssc.ic.llnwd.net/')
	Net::HTTP.start(url.host, url.port) do |http|       
	randomstring = ('A'..'Z').to_a.shuffle[0,6].join
	filepath = "/var/capthurits/".to_s + randomstring.to_s + ".mp3".to_s
	f5 = open(filepath, "w+b")
	buffer = Array.new(240)
        begin
            http.request_get('/stream/bbcwssc_mp1_ws-eieuk') do |resp|              
            resp.read_body do |segment|
		buffer[x] = segment
		x = x + 1
		break if x == 240              
            end
	    puts "outer x=".to_s + x.to_s
            for i in 2..240
		f5.write(buffer[i])
	    end
	    break if x == 240
            end
        ensure
            f5.close()
        end     
    end
  end
  
  # GET /capthurits
  # GET /capthurits.json
  def index
    me = david.new
    me.greets
    @capthurits = Capthurit.all
  end

  def hello
    puts "hello world passover"
  end


  # GET /capthurits/1
  # GET /capthurits/1.json
  def show
  end

  # GET /capthurits/new
  def new
    @capthurit = Capthurit.new
  end

  # GET /capthurits/1/edit
  def edit
  end

  # POST /capthurits
  # POST /capthurits.json
  def create
    @capthurit = Capthurit.new(capthurit_params)

    respond_to do |format|
      if @capthurit.save
        format.html { redirect_to @capthurit, notice: 'Capthurit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @capthurit }
      else
        format.html { render action: 'new' }
        format.json { render json: @capthurit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /capthurits/1
  # PATCH/PUT /capthurits/1.json
  def update
    respond_to do |format|
      if @capthurit.update(capthurit_params)
        format.html { redirect_to @capthurit, notice: 'Capthurit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @capthurit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /capthurits/1
  # DELETE /capthurits/1.json
  def destroy
    @capthurit.destroy
    respond_to do |format|
      format.html { redirect_to capthurits_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_capthurit
      @capthurit = Capthurit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def capthurit_params
      params.require(:capthurit).permit(:filename, :stationname, :capthurstart)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capthurits_helper.rb
module CapthuritsHelper
end

app/views/capthurits/_form.html.erb
<%= form_for(@capthurit) do |f| %>
  <% if @capthurit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@capthurit.errors.count, "error") %> prohibited this capthurit from being saved:</h2>

      <ul>
      <% @capthurit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :stationname %><br>
    <%= f.text_field :stationname %>
  </div>
  <div class="field">
    <%= f.label :capthurstart %><br>
    <%= f.datetime_select :capthurstart %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/capthurits/edit.html.erb
<h1>Editing capthurit</h1>

<%= render 'form' %>

<%= link_to 'Show', @capthurit %> |
<%= link_to 'Back', capthurits_path %>

app/views/capthurits/index.html.erb
<h1>Listing capthurits</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Stationname</th>
      <th>Capthurstart</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>


  <tbody>
    <% @capthurits.each do |capthurit| %>
      <tr>
        <td><%= capthurit.filename %></td>
        <td><%= capthurit.stationname %></td>
        <td><%= capthurit.capthurstart %></td>
        <td><%= link_to 'Show', capthurit %></td>
        <td><%= link_to 'Edit', edit_capthurit_path(capthurit) %></td>
        <td><%= link_to 'Destroy', capthurit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td> <%= link_to 'Howdy', capthurit, method: :hello, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Capthurit', new_capthurit_path %>

app/views/capthurits/new.html.erb
<h1>New capthurit</h1>

<%= render 'form' %>

<%= link_to 'Back', capthurits_path %>

app/views/capthurits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @capthurit.filename %>
</p>

<p>
  <strong>Stationname:</strong>
  <%= @capthurit.stationname %>
</p>

<p>
  <strong>Capthurstart:</strong>
  <%= @capthurit.capthurstart %>
</p>

<%= link_to 'Edit', edit_capthurit_path(@capthurit) %> |
<%= link_to 'Back', capthurits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Capthur</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>